### ISSUE TITLE
concurrent licenses count

### ISSUE THREAD

**Issue by percramer** [WildGums/Orc.LicenseManager#4]
Hi,

i have been looking for a good way to do concurrent licensing for a while. I looks like your wrapper for portable.licensing could do a good job. I want to use a central license server where the clients talk to, but i can't really seem to find which key is used for the concurrent license count. Is it the Quantity key?

Regards,

Per

**Comment by GeertvanHorrik** [comment]
Sorry for our late reply, we've been closed due to the holidays. You are right, the Quantity is used for the max concurrent licenses, see https://github.com/WildGums/Orc.LicenseManager/blob/develop/src/Orc.LicenseManager.Client/Orc.LicenseManager.Client.Shared/Extensions/LicenseExtensions.cs#L18 for more details.
